# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
{
    'name': 'Diagrama1',
    'version': '0.1',
    'author': 'Bachaco-ve',
    'website': 'http://www.bachaco.org.ve',
    'category': 'Desconocida',
    'sequence': 15,
    'summary': 'Desconocida',
    'description': """ Coloque la Descripción """,
    'depends': ['base'],
    'data': ['security/ir.model.access.csv', 'views/Diagrama1_view.xml', 'demo_data/demo.xml'],
    'demo': ['demo_data/demo.xml'],
    'css': ['static/src/less/Diagrama1.less'],
    'update_xml': [ ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'post_init_hook': 'load_demo_data', # Agregar el hook de inicialización
}

# __init__.py
def load_demo_data(cr, registry):
    from odoo.tools import convert_file
    from odoo.modules.module import get_module_resource
    demo = get_module_resource('Diagrama1', 'demo_data/demo.xml')
    if demo:
        with open(demo, 'rb') as f:
            convert_file(cr, f, None, 'Diagrama1', mode='init', noupdate=True, kind='demo')